# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
setup_travis

default_platform(:ios)

platform :ios do
  # desc "Description of what the lane does"
  # lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  # end

  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
   match(app_identifier: 'com.bundle.identifier', type: 'development', readonly: true)
   match(app_identifier: 'com.bundle.identifier', type: 'appstore', readonly: true)
  end

  desc 'Build the iOS application.'
  private_lane :build do
    certificates
    increment_build_number(xcodeproj: './ios/NorrisFacts.xcodeproj')
    gym(scheme: 'AppName', project: './ios/NorrisFacts.xcodeproj')

  desc 'Send to Testflight.'
  lane :beta do
    build
    pilot
    commit_version_bump(message: 'Bump build', xcodeproj: './ios/NorrisFacts.xcodeproj')
    push_to_git_remote
  end

end
